language: python
python:
  - "2.6"
  - "2.7"
env:
  - MAGRICULTURE_TEST_DB=postgres
install:
    - "pip install -r requirements.pip --use-mirrors"
before_script:
  - "psql -c \"create user magriculture with createdb password 'magriculture';\" -U postgres"
  - "psql -c 'create database magriculture owner magriculture;' -U postgres"
  - "export PYTHONPATH=."
  - "python ./manage.py syncdb --migrate --noinput --settings=magriculture.testsettings"
script:
    - ./run-tests-base.sh
